---
- name: apt update
  apt:
    update-cache: true

- name: apt install nginx
  apt:
    pkg: nginx
    state: latest

- name: Create directories
  file:
    dest: "/usr/share/nginx/html/{{ item }}"
    state: directory
  with_items: 
    - css
    - js

- name: Template a file to /etc/file.conf
  template:
    src: index.html
    dest: /usr/share/nginx/html/index.html

- name: Template a file to /etc/file.conf
  template:
    src: scripts.js
    dest: /usr/share/nginx/html/js/scripts.js

- name: Template a file to /etc/file.conf
  template:
    src: styles.css
    dest: /usr/share/nginx/html/css/styles.css

- name: Copy Nginx config file
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: start nginx
  service:
      name: nginx
      state: started
