---
- name: Copy Nodejs project
  copy: 
    src: back/
    dest: /back/   

- name: Install gnupg
  apt: 
    pkg: gnupg
    state: present
    update_cache: yes

- name: Install the gpg key for nodejs LTS
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs LTS repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install Nodejs
  apt:
    name: nodejs
    state: present

- name: npm install node_modules
  npm:
    path: "{{ directory }}"

- name: npm start
  shell: npm start &
  environment:
    PORT: "{{ back_port }}"
  args:
    chdir: "{{ directory }}"

- name: Check that you can connect (GET) to a page and it returns a status 200
  uri:
    url: "http://localhost:{{ back_port }}/api"
